AllCops:
  Exclude:
    - 'pkg/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - '*.gemspec'

Naming/FileName:
  Enabled: true
  Exclude:
    - 'lib/middleman-robots.rb'
