language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
rvm:
  - ruby-head
  - 2.6.4
  - 2.5.6
  - 2.4.7
os:
  - linux
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rubocop
  - bundle exec rake test
cache: bundler
env: TEST=true
